package database

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

// UserAPIKey represents a row from 'public.user_api_keys'.
type UserAPIKey struct {
	ID         uuid.UUID     `json:"id"`           // id
	UserID     uuid.UUID     `json:"user_id"`      // user_id
	Name       string        `json:"name"`         // name
	KeyHash    string        `json:"key_hash"`     // key_hash
	KeyPrefix  string        `json:"key_prefix"`   // key_prefix
	LastUsedAt sql.NullInt64 `json:"last_used_at"` // last_used_at
	CreatedAt  int64         `json:"created_at"`   // created_at
	UpdatedAt  int64         `json:"updated_at"`   // updated_at
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [UserAPIKey] exists in the database.
func (uak *UserAPIKey) Exists() bool {
	return uak._exists
}

// Deleted returns true when the [UserAPIKey] has been marked for deletion
// from the database.
func (uak *UserAPIKey) Deleted() bool {
	return uak._deleted
}

// Insert inserts the [UserAPIKey] to the database.
func (uak *UserAPIKey) Insert(ctx context.Context, db DB) error {
	switch {
	case uak._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case uak._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (manual)
	const sqlstr = `INSERT INTO public.user_api_keys (` +
		`id, user_id, name, key_hash, key_prefix, last_used_at, created_at, updated_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8` +
		`)`
	// run
	logf(sqlstr, uak.ID, uak.UserID, uak.Name, uak.KeyHash, uak.KeyPrefix, uak.LastUsedAt, uak.CreatedAt, uak.UpdatedAt)
	if _, err := db.ExecContext(ctx, sqlstr, uak.ID, uak.UserID, uak.Name, uak.KeyHash, uak.KeyPrefix, uak.LastUsedAt, uak.CreatedAt, uak.UpdatedAt); err != nil {
		return logerror(err)
	}
	// set exists
	uak._exists = true
	return nil
}

// Update updates a [UserAPIKey] in the database.
func (uak *UserAPIKey) Update(ctx context.Context, db DB) error {
	switch {
	case !uak._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case uak._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.user_api_keys SET ` +
		`user_id = $1, name = $2, key_hash = $3, key_prefix = $4, last_used_at = $5, created_at = $6, updated_at = $7 ` +
		`WHERE id = $8`
	// run
	logf(sqlstr, uak.UserID, uak.Name, uak.KeyHash, uak.KeyPrefix, uak.LastUsedAt, uak.CreatedAt, uak.UpdatedAt, uak.ID)
	if _, err := db.ExecContext(ctx, sqlstr, uak.UserID, uak.Name, uak.KeyHash, uak.KeyPrefix, uak.LastUsedAt, uak.CreatedAt, uak.UpdatedAt, uak.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [UserAPIKey] to the database.
func (uak *UserAPIKey) Save(ctx context.Context, db DB) error {
	if uak.Exists() {
		return uak.Update(ctx, db)
	}
	return uak.Insert(ctx, db)
}

// Upsert performs an upsert for [UserAPIKey].
func (uak *UserAPIKey) Upsert(ctx context.Context, db DB) error {
	switch {
	case uak._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.user_api_keys (` +
		`id, user_id, name, key_hash, key_prefix, last_used_at, created_at, updated_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`user_id = EXCLUDED.user_id, name = EXCLUDED.name, key_hash = EXCLUDED.key_hash, key_prefix = EXCLUDED.key_prefix, last_used_at = EXCLUDED.last_used_at, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at `
	// run
	logf(sqlstr, uak.ID, uak.UserID, uak.Name, uak.KeyHash, uak.KeyPrefix, uak.LastUsedAt, uak.CreatedAt, uak.UpdatedAt)
	if _, err := db.ExecContext(ctx, sqlstr, uak.ID, uak.UserID, uak.Name, uak.KeyHash, uak.KeyPrefix, uak.LastUsedAt, uak.CreatedAt, uak.UpdatedAt); err != nil {
		return logerror(err)
	}
	// set exists
	uak._exists = true
	return nil
}

// Delete deletes the [UserAPIKey] from the database.
func (uak *UserAPIKey) Delete(ctx context.Context, db DB) error {
	switch {
	case !uak._exists: // doesn't exist
		return nil
	case uak._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.user_api_keys ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, uak.ID)
	if _, err := db.ExecContext(ctx, sqlstr, uak.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	uak._deleted = true
	return nil
}

// UserAPIKeysByUserID retrieves a row from 'public.user_api_keys' as a [UserAPIKey].
//
// Generated from index 'idx_user_api_keys_user_id'.
func UserAPIKeysByUserID(ctx context.Context, db DB, userID uuid.UUID) ([]*UserAPIKey, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, user_id, name, key_hash, key_prefix, last_used_at, created_at, updated_at ` +
		`FROM public.user_api_keys ` +
		`WHERE user_id = $1`
	// run
	logf(sqlstr, userID)
	rows, err := db.QueryContext(ctx, sqlstr, userID)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*UserAPIKey
	for rows.Next() {
		uak := UserAPIKey{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&uak.ID, &uak.UserID, &uak.Name, &uak.KeyHash, &uak.KeyPrefix, &uak.LastUsedAt, &uak.CreatedAt, &uak.UpdatedAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &uak)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// UserAPIKeyByKeyHash retrieves a row from 'public.user_api_keys' as a [UserAPIKey].
//
// Generated from index 'user_api_keys_key_hash_key'.
func UserAPIKeyByKeyHash(ctx context.Context, db DB, keyHash string) (*UserAPIKey, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, user_id, name, key_hash, key_prefix, last_used_at, created_at, updated_at ` +
		`FROM public.user_api_keys ` +
		`WHERE key_hash = $1`
	// run
	logf(sqlstr, keyHash)
	uak := UserAPIKey{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, keyHash).Scan(&uak.ID, &uak.UserID, &uak.Name, &uak.KeyHash, &uak.KeyPrefix, &uak.LastUsedAt, &uak.CreatedAt, &uak.UpdatedAt); err != nil {
		return nil, logerror(err)
	}
	return &uak, nil
}

// UserAPIKeyByID retrieves a row from 'public.user_api_keys' as a [UserAPIKey].
//
// Generated from index 'user_api_keys_pkey'.
func UserAPIKeyByID(ctx context.Context, db DB, id uuid.UUID) (*UserAPIKey, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, user_id, name, key_hash, key_prefix, last_used_at, created_at, updated_at ` +
		`FROM public.user_api_keys ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	uak := UserAPIKey{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&uak.ID, &uak.UserID, &uak.Name, &uak.KeyHash, &uak.KeyPrefix, &uak.LastUsedAt, &uak.CreatedAt, &uak.UpdatedAt); err != nil {
		return nil, logerror(err)
	}
	return &uak, nil
}

// User returns the User associated with the [UserAPIKey]'s (UserID).
//
// Generated from foreign key 'user_api_keys_user_id_fkey'.
func (uak *UserAPIKey) User(ctx context.Context, db DB) (*User, error) {
	return UserByID(ctx, db, uak.UserID)
}
