version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
    groups:
      frontend:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/infra"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
    groups:
      docker:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
    groups:
      backend:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "swift"
    directory: "/ios"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
    groups:
      ios:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
    groups:
      github-actions:
        applies-to: security-updates
        patterns:
          - "*"
