version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    groups:
      frontend:
        applies-to: version-updates
        patterns:
          - "*"
      frontend-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/infra"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    groups:
      docker:
        applies-to: version-updates
        patterns:
          - "*"
      docker-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    groups:
      backend:
        applies-to: version-updates
        patterns:
          - "*"
      backend-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "swift"
    directory: "/ios"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    groups:
      ios:
        applies-to: version-updates
        patterns:
          - "*"
      ios-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
