frontend:
  - 'frontend/**/*'

backend:
  - 'backend/**/*'

proto:
  - 'proto/**/*'

database:
  - 'schema/**/*'

docker:
  - 'infra/**/*'
  - 'compose*.yml'
  - '**/Dockerfile'

docs:
  - 'adr/**/*'
  - '*.md'
  - 'LICENSE'

config:
  - 'Makefile'
  - '.github/**/*'
