services:
  backend:
    build:
      context: ./backend
      dockerfile: ../infra/dev/backend/Dockerfile
    volumes:
      - ./backend:/backend
      - ./proto:/proto # 内部で解決できるようにマウント
      - ./schema:/schema # pg-schema-diff用
    environment:
      TZ: Asia/Tokyo
      PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: dev-pass
      DB_NAME: umi_mikan
      JWT_SECRET: "hogehoge"
      TEST_DB_HOST: postgres_test
      TEST_DB_PORT: 5432
      TEST_DB_USER: postgres
      TEST_DB_PASSWORD: test-pass
      TEST_DB_NAME: umi_mikan_test
      REDIS_HOST: redis
      REDIS_PORT: 6379
    tty: true
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./frontend
      dockerfile: ../infra/dev/frontend/Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "5173:5173"
      # - "2802:2802" # playwright report
      # - "24678:24678" # hot relaod
    user: "1000:1000"
    volumes:
      - ./frontend:/frontend
      - ./proto:/proto # 内部で解決できるようにマウント

  postgres:
    image: postgres:17
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "dev-pass"
      POSTGRES_DB: "umi_mikan"
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d

  postgres_test:
    image: postgres:17
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "test-pass"
      POSTGRES_DB: "umi_mikan_test"
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_volume:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d

  redis:
    image: redis:8-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_volume:/data

  subscriber:
    build:
      context: ./backend
      dockerfile: ../infra/dev/subscriber/Dockerfile
    volumes:
      - ./backend:/backend
    environment:
      TZ: Asia/Tokyo
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: dev-pass
      DB_NAME: umi_mikan
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8082:8082"  # metrics endpoint
    tty: true
    depends_on:
      - postgres
      - redis

  scheduler:
    build:
      context: ./backend
      dockerfile: ../infra/dev/scheduler/Dockerfile
    volumes:
      - ./backend:/backend
    environment:
      TZ: Asia/Tokyo
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: dev-pass
      DB_NAME: umi_mikan
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8081:8081"  # metrics endpoint
    tty: true
    depends_on:
      - postgres
      - redis

  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_volume:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    depends_on:
      - scheduler
      - subscriber

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_volume:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  postgres_volume:
  postgres_test_volume:
  redis_volume:
  prometheus_volume:
  grafana_volume:
