services:
  backend:
    build:
      context: ./backend
      dockerfile: ../infra/dev/backend/Dockerfile
    volumes:
      - ./backend:/backend
    env_file:
      - .env
    environment:
      TZ: Asia/Tokyo
    tty: true
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./frontend
      dockerfile: ../infra/dev/frontend/Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "5173:5173"
      # - "2802:2802" # playwright report
      # - "24678:24678" # hot relaod
    user: "1000:1000"
    volumes:
      - ./frontend:/frontend

  postgres:
    image: postgres:16
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "umi_mikan"
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./infra/dev/postgres/init:/docker-entrypoint-initdb.d

volumes:
  postgres_volume:
