services:
  backend:
    build:
      context: ./backend
      dockerfile: ../infra/prod/backend/Dockerfile
    volumes:
      - ./schema:/schema # pg-schema-diff用
    environment:
      TZ: Asia/Tokyo
      PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: prod-pass
      DB_NAME: umi_mikan
      JWT_SECRET: prod-secret
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: ../infra/prod/frontend/Dockerfile
    environment:
      TZ: Asia/Tokyo
      NODE_ENV: production
      BODY_SIZE_LIMIT: 1M
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - internal

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prod-pass
      POSTGRES_DB: umi_mikan
    volumes:
      - postgres_prod_volume:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d umi_mikan"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - internal

  # Development tools service for running database migrations and other dev tasks
  dev-tools:
    build:
      context: ./backend
      dockerfile: ../infra/prod/dev-tools/Dockerfile
    volumes:
      - ./backend:/backend
      - ./proto:/proto
      - ./schema:/schema
    environment:
      TZ: Asia/Tokyo
      PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: prod-pass
      DB_NAME: umi_mikan
      JWT_SECRET: prod-secret
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
    profiles:
      - dev-tools

  tunnel:
    restart: always
    image: cloudflare/cloudflared
    command: tunnel run
    depends_on:
      - frontend
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    networks:
      - internal

volumes:
  postgres_prod_volume:

networks:
  internal:
    driver: bridge
