global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "scheduler"
    static_configs:
      - targets: ["scheduler:2006"]
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: "subscriber"
    static_configs:
      - targets: ["subscriber:2005"]
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 15s

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 15s
    metrics_path: /metrics
