// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: user/user.proto
//

import Connect
import Foundation
import SwiftProtobuf

/// UserService はユーザー設定とアカウント管理を提供するサービスです。
/// ユーザー情報の更新、AI機能の有効化、自動要約設定、Pub/Subメトリクス取得などの機能があります。
internal protocol User_UserServiceClientInterface: Sendable {

    /// UpdateUserName はユーザー名を変更します。
    ///
    /// 例:
    ///   request: { new_name: "新しい名前" }
    ///   response: { success: true, message: "ユーザー名を更新しました" }
    ///
    /// エラー:
    ///   - InvalidArgument: 名前が空
    ///   - Internal: データベースエラー
    @available(iOS 13, *)
    func `updateUserName`(request: User_UpdateUserNameRequest, headers: Connect.Headers) async -> ResponseMessage<User_UpdateUserNameResponse>

    /// ChangePassword は現在のパスワードを検証して新しいパスワードに変更します。
    ///
    /// 例:
    ///   request: { current_password: "old123", new_password: "new456" }
    ///   response: { success: true, message: "パスワードを変更しました" }
    ///
    /// エラー:
    ///   - Unauthenticated: 現在のパスワードが不正
    ///   - InvalidArgument: 新しいパスワードが短すぎる
    @available(iOS 13, *)
    func `changePassword`(request: User_ChangePasswordRequest, headers: Connect.Headers) async -> ResponseMessage<User_ChangePasswordResponse>

    /// EnableLLM はユーザーのAI機能（要約・ハイライト・意味的検索など）を有効化（オプトイン）します。
    /// LLMは共通GCPプロジェクトのVertex AI経由で呼び出すため、ユーザーがAPIキーを用意する必要はありません。
    /// 現在はGemini (llm_provider=1) のみ対応しています。既に有効な場合は何もせず成功を返します。
    ///
    /// 例:
    ///   request: { llm_provider: 1 }
    ///   response: { success: true, message: "llmEnabled" }
    ///
    /// エラー:
    ///   - InvalidArgument: プロバイダーが不正
    @available(iOS 13, *)
    func `enableLlm`(request: User_EnableLLMRequest, headers: Connect.Headers) async -> ResponseMessage<User_EnableLLMResponse>

    /// GetUserInfo はユーザーの基本情報とAI機能設定を取得します。
    ///
    /// 例:
    ///   request: {}
    ///   response: { name: "太郎", email: "user@example.com", llm_settings: [{ llm_provider: 1, ... }] }
    ///
    /// エラー:
    ///   - NotFound: ユーザーが存在しない（通常発生しない、認証済みのため）
    @available(iOS 13, *)
    func `getUserInfo`(request: User_GetUserInfoRequest, headers: Connect.Headers) async -> ResponseMessage<User_GetUserInfoResponse>

    /// DisableLLM はユーザーのAI機能を無効化（オプトアウト）します。自動要約などの設定も削除されます。
    ///
    /// 例:
    ///   request: { llm_provider: 1 }
    ///   response: { success: true, message: "llmDisabled" }
    ///
    /// エラー:
    ///   - NotFound: 指定されたプロバイダーのAI機能が有効化されていない
    @available(iOS 13, *)
    func `disableLlm`(request: User_DisableLLMRequest, headers: Connect.Headers) async -> ResponseMessage<User_DisableLLMResponse>

    /// DeleteAccount はユーザーアカウントと関連データを完全に削除します。
    /// 日記、エンティティ、要約など全てのデータがカスケード削除されます。
    ///
    /// 例:
    ///   request: {}
    ///   response: { success: true, message: "アカウントを削除しました" }
    ///
    /// エラー:
    ///   - Internal: 削除処理エラー
    @available(iOS 13, *)
    func `deleteAccount`(request: User_DeleteAccountRequest, headers: Connect.Headers) async -> ResponseMessage<User_DeleteAccountResponse>

    /// UpdateAutoSummarySettings は自動要約生成の設定を更新します。
    /// 月次要約を有効/無効にできます。
    ///
    /// 例:
    ///   request: { llm_provider: 1, auto_summary_monthly: false }
    ///   response: { success: true, message: "自動要約設定を更新しました" }
    ///
    /// エラー:
    ///   - NotFound: AI機能が有効化されていない
    @available(iOS 13, *)
    func `updateAutoSummarySettings`(request: User_UpdateAutoSummarySettingsRequest, headers: Connect.Headers) async -> ResponseMessage<User_UpdateAutoSummarySettingsResponse>

    /// GetAutoSummarySettings は自動要約生成の現在の設定を取得します。
    ///
    /// 例:
    ///   request: { llm_provider: 1 }
    ///   response: { auto_summary_monthly: false }
    ///
    /// エラー:
    ///   - NotFound: AI機能が有効化されていない
    @available(iOS 13, *)
    func `getAutoSummarySettings`(request: User_GetAutoSummarySettingsRequest, headers: Connect.Headers) async -> ResponseMessage<User_GetAutoSummarySettingsResponse>

    /// GetPubSubMetrics はRedis Pub/Subによる要約生成タスクの処理状況を取得します。
    /// 過去24時間の時間別メトリクス、現在処理中のタスク、統計情報が含まれます。
    ///
    /// 例:
    ///   request: {}
    ///   response: { hourly_metrics: [...], processing_tasks: [...], summary: { total_daily_summaries: 10, ... } }
    ///
    /// エラー: なし（データがない場合は空配列）
    @available(iOS 13, *)
    func `getPubSubMetrics`(request: User_GetPubSubMetricsRequest, headers: Connect.Headers) async -> ResponseMessage<User_GetPubSubMetricsResponse>

    /// CreateApiKey はMCPサーバーなど外部クライアント向けのAPIキーを発行します。
    /// キー本体はレスポンスで一度だけ返され、サーバーにはハッシュのみ保存されます。
    ///
    /// 例:
    ///   request: { name: "Claude Desktop" }
    ///   response: { api_key: "umi_...", info: { id: "...", name: "Claude Desktop", key_prefix: "umi_a1b2c3d4", ... } }
    ///
    /// エラー:
    ///   - InvalidArgument: 名前が空または長すぎる
    ///   - Internal: データベースエラー
    @available(iOS 13, *)
    func `createApiKey`(request: User_CreateApiKeyRequest, headers: Connect.Headers) async -> ResponseMessage<User_CreateApiKeyResponse>

    /// ListApiKeys は発行済みAPIキーの一覧を返します（キー本体は含まれません）。
    ///
    /// 例:
    ///   request: {}
    ///   response: { api_keys: [{ id: "...", name: "Claude Desktop", key_prefix: "umi_a1b2c3d4", ... }] }
    ///
    /// エラー: なし（キーがない場合は空配列）
    @available(iOS 13, *)
    func `listApiKeys`(request: User_ListApiKeysRequest, headers: Connect.Headers) async -> ResponseMessage<User_ListApiKeysResponse>

    /// DeleteApiKey は指定されたAPIキーを失効させます。
    ///
    /// 例:
    ///   request: { id: "..." }
    ///   response: { success: true, message: "APIキーを削除しました" }
    ///
    /// エラー:
    ///   - NotFound: 指定されたキーが存在しない、または他ユーザーのキー
    @available(iOS 13, *)
    func `deleteApiKey`(request: User_DeleteApiKeyRequest, headers: Connect.Headers) async -> ResponseMessage<User_DeleteApiKeyResponse>
}

/// Concrete implementation of `User_UserServiceClientInterface`.
internal final class User_UserServiceClient: User_UserServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    internal init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    internal func `updateUserName`(request: User_UpdateUserNameRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_UpdateUserNameResponse> {
        return await self.client.unary(path: "/user.UserService/UpdateUserName", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `changePassword`(request: User_ChangePasswordRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_ChangePasswordResponse> {
        return await self.client.unary(path: "/user.UserService/ChangePassword", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `enableLlm`(request: User_EnableLLMRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_EnableLLMResponse> {
        return await self.client.unary(path: "/user.UserService/EnableLLM", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `getUserInfo`(request: User_GetUserInfoRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_GetUserInfoResponse> {
        return await self.client.unary(path: "/user.UserService/GetUserInfo", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `disableLlm`(request: User_DisableLLMRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_DisableLLMResponse> {
        return await self.client.unary(path: "/user.UserService/DisableLLM", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `deleteAccount`(request: User_DeleteAccountRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_DeleteAccountResponse> {
        return await self.client.unary(path: "/user.UserService/DeleteAccount", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `updateAutoSummarySettings`(request: User_UpdateAutoSummarySettingsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_UpdateAutoSummarySettingsResponse> {
        return await self.client.unary(path: "/user.UserService/UpdateAutoSummarySettings", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `getAutoSummarySettings`(request: User_GetAutoSummarySettingsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_GetAutoSummarySettingsResponse> {
        return await self.client.unary(path: "/user.UserService/GetAutoSummarySettings", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `getPubSubMetrics`(request: User_GetPubSubMetricsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_GetPubSubMetricsResponse> {
        return await self.client.unary(path: "/user.UserService/GetPubSubMetrics", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `createApiKey`(request: User_CreateApiKeyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_CreateApiKeyResponse> {
        return await self.client.unary(path: "/user.UserService/CreateApiKey", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `listApiKeys`(request: User_ListApiKeysRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_ListApiKeysResponse> {
        return await self.client.unary(path: "/user.UserService/ListApiKeys", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `deleteApiKey`(request: User_DeleteApiKeyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_DeleteApiKeyResponse> {
        return await self.client.unary(path: "/user.UserService/DeleteApiKey", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    internal enum Metadata {
        internal enum Methods {
            internal static let updateUserName = Connect.MethodSpec(name: "UpdateUserName", service: "user.UserService", type: .unary)
            internal static let changePassword = Connect.MethodSpec(name: "ChangePassword", service: "user.UserService", type: .unary)
            internal static let enableLlm = Connect.MethodSpec(name: "EnableLLM", service: "user.UserService", type: .unary)
            internal static let getUserInfo = Connect.MethodSpec(name: "GetUserInfo", service: "user.UserService", type: .unary)
            internal static let disableLlm = Connect.MethodSpec(name: "DisableLLM", service: "user.UserService", type: .unary)
            internal static let deleteAccount = Connect.MethodSpec(name: "DeleteAccount", service: "user.UserService", type: .unary)
            internal static let updateAutoSummarySettings = Connect.MethodSpec(name: "UpdateAutoSummarySettings", service: "user.UserService", type: .unary)
            internal static let getAutoSummarySettings = Connect.MethodSpec(name: "GetAutoSummarySettings", service: "user.UserService", type: .unary)
            internal static let getPubSubMetrics = Connect.MethodSpec(name: "GetPubSubMetrics", service: "user.UserService", type: .unary)
            internal static let createApiKey = Connect.MethodSpec(name: "CreateApiKey", service: "user.UserService", type: .unary)
            internal static let listApiKeys = Connect.MethodSpec(name: "ListApiKeys", service: "user.UserService", type: .unary)
            internal static let deleteApiKey = Connect.MethodSpec(name: "DeleteApiKey", service: "user.UserService", type: .unary)
        }
    }
}
