// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: user/user.proto
//

import Connect
import Foundation
import SwiftProtobuf

/// UserService はユーザー設定とアカウント管理を提供するサービスです。
/// ユーザー情報の更新、LLMキー管理、自動要約設定、Pub/Subメトリクス取得などの機能があります。
internal protocol User_UserServiceClientInterface: Sendable {

    /// UpdateUserName はユーザー名を変更します。
    ///
    /// 例:
    ///   request: { new_name: "新しい名前" }
    ///   response: { success: true, message: "ユーザー名を更新しました" }
    ///
    /// エラー:
    ///   - InvalidArgument: 名前が空
    ///   - Internal: データベースエラー
    @available(iOS 13, *)
    func `updateUserName`(request: User_UpdateUserNameRequest, headers: Connect.Headers) async -> ResponseMessage<User_UpdateUserNameResponse>

    /// ChangePassword は現在のパスワードを検証して新しいパスワードに変更します。
    ///
    /// 例:
    ///   request: { current_password: "old123", new_password: "new456" }
    ///   response: { success: true, message: "パスワードを変更しました" }
    ///
    /// エラー:
    ///   - Unauthenticated: 現在のパスワードが不正
    ///   - InvalidArgument: 新しいパスワードが短すぎる
    @available(iOS 13, *)
    func `changePassword`(request: User_ChangePasswordRequest, headers: Connect.Headers) async -> ResponseMessage<User_ChangePasswordResponse>

    /// UpdateLLMKey はLLM APIキーを更新または新規作成します。
    /// 現在はGemini (llm_provider=1) のみ対応しています。
    ///
    /// 例:
    ///   request: { llm_provider: 1, key: "AIza..." }
    ///   response: { success: true, message: "LLMキーを更新しました" }
    ///
    /// エラー:
    ///   - InvalidArgument: プロバイダーまたはキーが不正
    @available(iOS 13, *)
    func `updateLlmkey`(request: User_UpdateLLMKeyRequest, headers: Connect.Headers) async -> ResponseMessage<User_UpdateLLMKeyResponse>

    /// GetUserInfo はユーザーの基本情報とLLMキー設定を取得します。
    ///
    /// 例:
    ///   request: {}
    ///   response: { name: "太郎", email: "user@example.com", llm_keys: [{ llm_provider: 1, ... }] }
    ///
    /// エラー:
    ///   - NotFound: ユーザーが存在しない（通常発生しない、認証済みのため）
    @available(iOS 13, *)
    func `getUserInfo`(request: User_GetUserInfoRequest, headers: Connect.Headers) async -> ResponseMessage<User_GetUserInfoResponse>

    /// DeleteLLMKey は指定されたLLM APIキーを削除します。
    ///
    /// 例:
    ///   request: { llm_provider: 1 }
    ///   response: { success: true, message: "LLMキーを削除しました" }
    ///
    /// エラー:
    ///   - NotFound: 指定されたプロバイダーのキーが存在しない
    @available(iOS 13, *)
    func `deleteLlmkey`(request: User_DeleteLLMKeyRequest, headers: Connect.Headers) async -> ResponseMessage<User_DeleteLLMKeyResponse>

    /// DeleteAccount はユーザーアカウントと関連データを完全に削除します。
    /// 日記、エンティティ、要約など全てのデータがカスケード削除されます。
    ///
    /// 例:
    ///   request: {}
    ///   response: { success: true, message: "アカウントを削除しました" }
    ///
    /// エラー:
    ///   - Internal: 削除処理エラー
    @available(iOS 13, *)
    func `deleteAccount`(request: User_DeleteAccountRequest, headers: Connect.Headers) async -> ResponseMessage<User_DeleteAccountResponse>

    /// UpdateAutoSummarySettings は自動要約生成の設定を更新します。
    /// 月次要約を有効/無効にできます。
    ///
    /// 例:
    ///   request: { llm_provider: 1, auto_summary_monthly: false }
    ///   response: { success: true, message: "自動要約設定を更新しました" }
    ///
    /// エラー:
    ///   - NotFound: LLMキーが設定されていない
    @available(iOS 13, *)
    func `updateAutoSummarySettings`(request: User_UpdateAutoSummarySettingsRequest, headers: Connect.Headers) async -> ResponseMessage<User_UpdateAutoSummarySettingsResponse>

    /// GetAutoSummarySettings は自動要約生成の現在の設定を取得します。
    ///
    /// 例:
    ///   request: { llm_provider: 1 }
    ///   response: { auto_summary_monthly: false }
    ///
    /// エラー:
    ///   - NotFound: LLMキーが設定されていない
    @available(iOS 13, *)
    func `getAutoSummarySettings`(request: User_GetAutoSummarySettingsRequest, headers: Connect.Headers) async -> ResponseMessage<User_GetAutoSummarySettingsResponse>

    /// GetPubSubMetrics はRedis Pub/Subによる要約生成タスクの処理状況を取得します。
    /// 過去24時間の時間別メトリクス、現在処理中のタスク、統計情報が含まれます。
    ///
    /// 例:
    ///   request: {}
    ///   response: { hourly_metrics: [...], processing_tasks: [...], summary: { total_daily_summaries: 10, ... } }
    ///
    /// エラー: なし（データがない場合は空配列）
    @available(iOS 13, *)
    func `getPubSubMetrics`(request: User_GetPubSubMetricsRequest, headers: Connect.Headers) async -> ResponseMessage<User_GetPubSubMetricsResponse>
}

/// Concrete implementation of `User_UserServiceClientInterface`.
internal final class User_UserServiceClient: User_UserServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    internal init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    internal func `updateUserName`(request: User_UpdateUserNameRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_UpdateUserNameResponse> {
        return await self.client.unary(path: "/user.UserService/UpdateUserName", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `changePassword`(request: User_ChangePasswordRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_ChangePasswordResponse> {
        return await self.client.unary(path: "/user.UserService/ChangePassword", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `updateLlmkey`(request: User_UpdateLLMKeyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_UpdateLLMKeyResponse> {
        return await self.client.unary(path: "/user.UserService/UpdateLLMKey", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `getUserInfo`(request: User_GetUserInfoRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_GetUserInfoResponse> {
        return await self.client.unary(path: "/user.UserService/GetUserInfo", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `deleteLlmkey`(request: User_DeleteLLMKeyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_DeleteLLMKeyResponse> {
        return await self.client.unary(path: "/user.UserService/DeleteLLMKey", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `deleteAccount`(request: User_DeleteAccountRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_DeleteAccountResponse> {
        return await self.client.unary(path: "/user.UserService/DeleteAccount", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `updateAutoSummarySettings`(request: User_UpdateAutoSummarySettingsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_UpdateAutoSummarySettingsResponse> {
        return await self.client.unary(path: "/user.UserService/UpdateAutoSummarySettings", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `getAutoSummarySettings`(request: User_GetAutoSummarySettingsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_GetAutoSummarySettingsResponse> {
        return await self.client.unary(path: "/user.UserService/GetAutoSummarySettings", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `getPubSubMetrics`(request: User_GetPubSubMetricsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<User_GetPubSubMetricsResponse> {
        return await self.client.unary(path: "/user.UserService/GetPubSubMetrics", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    internal enum Metadata {
        internal enum Methods {
            internal static let updateUserName = Connect.MethodSpec(name: "UpdateUserName", service: "user.UserService", type: .unary)
            internal static let changePassword = Connect.MethodSpec(name: "ChangePassword", service: "user.UserService", type: .unary)
            internal static let updateLlmkey = Connect.MethodSpec(name: "UpdateLLMKey", service: "user.UserService", type: .unary)
            internal static let getUserInfo = Connect.MethodSpec(name: "GetUserInfo", service: "user.UserService", type: .unary)
            internal static let deleteLlmkey = Connect.MethodSpec(name: "DeleteLLMKey", service: "user.UserService", type: .unary)
            internal static let deleteAccount = Connect.MethodSpec(name: "DeleteAccount", service: "user.UserService", type: .unary)
            internal static let updateAutoSummarySettings = Connect.MethodSpec(name: "UpdateAutoSummarySettings", service: "user.UserService", type: .unary)
            internal static let getAutoSummarySettings = Connect.MethodSpec(name: "GetAutoSummarySettings", service: "user.UserService", type: .unary)
            internal static let getPubSubMetrics = Connect.MethodSpec(name: "GetPubSubMetrics", service: "user.UserService", type: .unary)
        }
    }
}
