// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: diary/diary.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type YMD struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          uint32                 `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         uint32                 `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day           uint32                 `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YMD) Reset() {
	*x = YMD{}
	mi := &file_diary_diary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YMD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YMD) ProtoMessage() {}

func (x *YMD) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YMD.ProtoReflect.Descriptor instead.
func (*YMD) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{0}
}

func (x *YMD) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *YMD) GetMonth() uint32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *YMD) GetDay() uint32 {
	if x != nil {
		return x.Day
	}
	return 0
}

type YM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          uint32                 `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         uint32                 `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YM) Reset() {
	*x = YM{}
	mi := &file_diary_diary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YM) ProtoMessage() {}

func (x *YM) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YM.ProtoReflect.Descriptor instead.
func (*YM) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{1}
}

func (x *YM) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *YM) GetMonth() uint32 {
	if x != nil {
		return x.Month
	}
	return 0
}

// 日記エントリのメッセージ
type DiaryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // 日記ID
	Date          *YMD                   `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`                             // 日付
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                       // 内容
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 作成日時（Unix timestamp）
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 更新日時（Unix timestamp）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiaryEntry) Reset() {
	*x = DiaryEntry{}
	mi := &file_diary_diary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiaryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiaryEntry) ProtoMessage() {}

func (x *DiaryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiaryEntry.ProtoReflect.Descriptor instead.
func (*DiaryEntry) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{2}
}

func (x *DiaryEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DiaryEntry) GetDate() *YMD {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *DiaryEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DiaryEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DiaryEntry) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 新しい日記エントリを作成するためのリクエスト
type CreateDiaryEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Date          *YMD                   `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDiaryEntryRequest) Reset() {
	*x = CreateDiaryEntryRequest{}
	mi := &file_diary_diary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDiaryEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDiaryEntryRequest) ProtoMessage() {}

func (x *CreateDiaryEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDiaryEntryRequest.ProtoReflect.Descriptor instead.
func (*CreateDiaryEntryRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDiaryEntryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateDiaryEntryRequest) GetDate() *YMD {
	if x != nil {
		return x.Date
	}
	return nil
}

// 日記エントリを作成した結果を返すレスポンス
type CreateDiaryEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *DiaryEntry            `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDiaryEntryResponse) Reset() {
	*x = CreateDiaryEntryResponse{}
	mi := &file_diary_diary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDiaryEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDiaryEntryResponse) ProtoMessage() {}

func (x *CreateDiaryEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDiaryEntryResponse.ProtoReflect.Descriptor instead.
func (*CreateDiaryEntryResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDiaryEntryResponse) GetEntry() *DiaryEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// 特定の日記エントリを取得するためのリクエスト
type GetDiaryEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *YMD                   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // 日付を指定して取得
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiaryEntryRequest) Reset() {
	*x = GetDiaryEntryRequest{}
	mi := &file_diary_diary_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiaryEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiaryEntryRequest) ProtoMessage() {}

func (x *GetDiaryEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiaryEntryRequest.ProtoReflect.Descriptor instead.
func (*GetDiaryEntryRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{5}
}

func (x *GetDiaryEntryRequest) GetDate() *YMD {
	if x != nil {
		return x.Date
	}
	return nil
}

// 複数日記エントリを取得するためのリクエスト (e.g., by range or count)
type GetDiaryEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dates         []*YMD                 `protobuf:"bytes,1,rep,name=dates,proto3" json:"dates,omitempty"` // 取得したい日付の配列
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiaryEntriesRequest) Reset() {
	*x = GetDiaryEntriesRequest{}
	mi := &file_diary_diary_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiaryEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiaryEntriesRequest) ProtoMessage() {}

func (x *GetDiaryEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiaryEntriesRequest.ProtoReflect.Descriptor instead.
func (*GetDiaryEntriesRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{6}
}

func (x *GetDiaryEntriesRequest) GetDates() []*YMD {
	if x != nil {
		return x.Dates
	}
	return nil
}

// 月ごとに日記エントリを取得するためのリクエスト
type GetDiaryEntriesByMonthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         *YM                    `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"` // 年月を指定
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiaryEntriesByMonthRequest) Reset() {
	*x = GetDiaryEntriesByMonthRequest{}
	mi := &file_diary_diary_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiaryEntriesByMonthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiaryEntriesByMonthRequest) ProtoMessage() {}

func (x *GetDiaryEntriesByMonthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiaryEntriesByMonthRequest.ProtoReflect.Descriptor instead.
func (*GetDiaryEntriesByMonthRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{7}
}

func (x *GetDiaryEntriesByMonthRequest) GetMonth() *YM {
	if x != nil {
		return x.Month
	}
	return nil
}

type SearchDiaryEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchDiaryEntriesRequest) Reset() {
	*x = SearchDiaryEntriesRequest{}
	mi := &file_diary_diary_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDiaryEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDiaryEntriesRequest) ProtoMessage() {}

func (x *SearchDiaryEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDiaryEntriesRequest.ProtoReflect.Descriptor instead.
func (*SearchDiaryEntriesRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{8}
}

func (x *SearchDiaryEntriesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type SearchDiaryEntriesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SearchedKeyword string                 `protobuf:"bytes,1,opt,name=searched_keyword,json=searchedKeyword,proto3" json:"searched_keyword,omitempty"` // 実際に検索した単語
	Entries         []*DiaryEntry          `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchDiaryEntriesResponse) Reset() {
	*x = SearchDiaryEntriesResponse{}
	mi := &file_diary_diary_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDiaryEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDiaryEntriesResponse) ProtoMessage() {}

func (x *SearchDiaryEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDiaryEntriesResponse.ProtoReflect.Descriptor instead.
func (*SearchDiaryEntriesResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{9}
}

func (x *SearchDiaryEntriesResponse) GetSearchedKeyword() string {
	if x != nil {
		return x.SearchedKeyword
	}
	return ""
}

func (x *SearchDiaryEntriesResponse) GetEntries() []*DiaryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetDiaryEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DiaryEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiaryEntriesResponse) Reset() {
	*x = GetDiaryEntriesResponse{}
	mi := &file_diary_diary_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiaryEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiaryEntriesResponse) ProtoMessage() {}

func (x *GetDiaryEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiaryEntriesResponse.ProtoReflect.Descriptor instead.
func (*GetDiaryEntriesResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{10}
}

func (x *GetDiaryEntriesResponse) GetEntries() []*DiaryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetDiaryEntriesByMonthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DiaryEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiaryEntriesByMonthResponse) Reset() {
	*x = GetDiaryEntriesByMonthResponse{}
	mi := &file_diary_diary_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiaryEntriesByMonthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiaryEntriesByMonthResponse) ProtoMessage() {}

func (x *GetDiaryEntriesByMonthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiaryEntriesByMonthResponse.ProtoReflect.Descriptor instead.
func (*GetDiaryEntriesByMonthResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{11}
}

func (x *GetDiaryEntriesByMonthResponse) GetEntries() []*DiaryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// 日記エントリを取得した結果を返すレスポンス
type GetDiaryEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *DiaryEntry            `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiaryEntryResponse) Reset() {
	*x = GetDiaryEntryResponse{}
	mi := &file_diary_diary_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiaryEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiaryEntryResponse) ProtoMessage() {}

func (x *GetDiaryEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiaryEntryResponse.ProtoReflect.Descriptor instead.
func (*GetDiaryEntryResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{12}
}

func (x *GetDiaryEntryResponse) GetEntry() *DiaryEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// 日記エントリを更新するためのリクエスト
type UpdateDiaryEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Date          *YMD                   `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDiaryEntryRequest) Reset() {
	*x = UpdateDiaryEntryRequest{}
	mi := &file_diary_diary_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDiaryEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDiaryEntryRequest) ProtoMessage() {}

func (x *UpdateDiaryEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDiaryEntryRequest.ProtoReflect.Descriptor instead.
func (*UpdateDiaryEntryRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateDiaryEntryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDiaryEntryRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateDiaryEntryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateDiaryEntryRequest) GetDate() *YMD {
	if x != nil {
		return x.Date
	}
	return nil
}

// 更新された日記エントリを返すレスポンス
type UpdateDiaryEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *DiaryEntry            `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDiaryEntryResponse) Reset() {
	*x = UpdateDiaryEntryResponse{}
	mi := &file_diary_diary_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDiaryEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDiaryEntryResponse) ProtoMessage() {}

func (x *UpdateDiaryEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDiaryEntryResponse.ProtoReflect.Descriptor instead.
func (*UpdateDiaryEntryResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateDiaryEntryResponse) GetEntry() *DiaryEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// 日記エントリを削除するためのリクエスト
type DeleteDiaryEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDiaryEntryRequest) Reset() {
	*x = DeleteDiaryEntryRequest{}
	mi := &file_diary_diary_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDiaryEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDiaryEntryRequest) ProtoMessage() {}

func (x *DeleteDiaryEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDiaryEntryRequest.ProtoReflect.Descriptor instead.
func (*DeleteDiaryEntryRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteDiaryEntryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 削除操作の結果を返すレスポンス
type DeleteDiaryEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDiaryEntryResponse) Reset() {
	*x = DeleteDiaryEntryResponse{}
	mi := &file_diary_diary_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDiaryEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDiaryEntryResponse) ProtoMessage() {}

func (x *DeleteDiaryEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDiaryEntryResponse.ProtoReflect.Descriptor instead.
func (*DeleteDiaryEntryResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteDiaryEntryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 月サマリー
type MonthlySummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Month         *YM                    `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlySummary) Reset() {
	*x = MonthlySummary{}
	mi := &file_diary_diary_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlySummary) ProtoMessage() {}

func (x *MonthlySummary) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlySummary.ProtoReflect.Descriptor instead.
func (*MonthlySummary) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{17}
}

func (x *MonthlySummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MonthlySummary) GetMonth() *YM {
	if x != nil {
		return x.Month
	}
	return nil
}

func (x *MonthlySummary) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *MonthlySummary) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MonthlySummary) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 月ごとのサマリー生成リクエスト
type GenerateMonthlySummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         *YM                    `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateMonthlySummaryRequest) Reset() {
	*x = GenerateMonthlySummaryRequest{}
	mi := &file_diary_diary_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateMonthlySummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateMonthlySummaryRequest) ProtoMessage() {}

func (x *GenerateMonthlySummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateMonthlySummaryRequest.ProtoReflect.Descriptor instead.
func (*GenerateMonthlySummaryRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{18}
}

func (x *GenerateMonthlySummaryRequest) GetMonth() *YM {
	if x != nil {
		return x.Month
	}
	return nil
}

// 月ごとのサマリー生成レスポンス
type GenerateMonthlySummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *MonthlySummary        `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateMonthlySummaryResponse) Reset() {
	*x = GenerateMonthlySummaryResponse{}
	mi := &file_diary_diary_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateMonthlySummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateMonthlySummaryResponse) ProtoMessage() {}

func (x *GenerateMonthlySummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateMonthlySummaryResponse.ProtoReflect.Descriptor instead.
func (*GenerateMonthlySummaryResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{19}
}

func (x *GenerateMonthlySummaryResponse) GetSummary() *MonthlySummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

// 月ごとのサマリー取得リクエスト
type GetMonthlySummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         *YM                    `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthlySummaryRequest) Reset() {
	*x = GetMonthlySummaryRequest{}
	mi := &file_diary_diary_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlySummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlySummaryRequest) ProtoMessage() {}

func (x *GetMonthlySummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlySummaryRequest.ProtoReflect.Descriptor instead.
func (*GetMonthlySummaryRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{20}
}

func (x *GetMonthlySummaryRequest) GetMonth() *YM {
	if x != nil {
		return x.Month
	}
	return nil
}

// 月ごとのサマリー取得レスポンス
type GetMonthlySummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *MonthlySummary        `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthlySummaryResponse) Reset() {
	*x = GetMonthlySummaryResponse{}
	mi := &file_diary_diary_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlySummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlySummaryResponse) ProtoMessage() {}

func (x *GetMonthlySummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlySummaryResponse.ProtoReflect.Descriptor instead.
func (*GetMonthlySummaryResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{21}
}

func (x *GetMonthlySummaryResponse) GetSummary() *MonthlySummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

// 日サマリー
type DailySummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DiaryId       string                 `protobuf:"bytes,2,opt,name=diary_id,json=diaryId,proto3" json:"diary_id,omitempty"`
	Date          *YMD                   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailySummary) Reset() {
	*x = DailySummary{}
	mi := &file_diary_diary_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailySummary) ProtoMessage() {}

func (x *DailySummary) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailySummary.ProtoReflect.Descriptor instead.
func (*DailySummary) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{22}
}

func (x *DailySummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DailySummary) GetDiaryId() string {
	if x != nil {
		return x.DiaryId
	}
	return ""
}

func (x *DailySummary) GetDate() *YMD {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *DailySummary) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *DailySummary) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DailySummary) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 日ごとのサマリー生成リクエスト
type GenerateDailySummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiaryId       string                 `protobuf:"bytes,1,opt,name=diary_id,json=diaryId,proto3" json:"diary_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDailySummaryRequest) Reset() {
	*x = GenerateDailySummaryRequest{}
	mi := &file_diary_diary_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDailySummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDailySummaryRequest) ProtoMessage() {}

func (x *GenerateDailySummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDailySummaryRequest.ProtoReflect.Descriptor instead.
func (*GenerateDailySummaryRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{23}
}

func (x *GenerateDailySummaryRequest) GetDiaryId() string {
	if x != nil {
		return x.DiaryId
	}
	return ""
}

// 日ごとのサマリー生成レスポンス
type GenerateDailySummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *DailySummary          `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDailySummaryResponse) Reset() {
	*x = GenerateDailySummaryResponse{}
	mi := &file_diary_diary_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDailySummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDailySummaryResponse) ProtoMessage() {}

func (x *GenerateDailySummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDailySummaryResponse.ProtoReflect.Descriptor instead.
func (*GenerateDailySummaryResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{24}
}

func (x *GenerateDailySummaryResponse) GetSummary() *DailySummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

// 日ごとのサマリー取得リクエスト
type GetDailySummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *YMD                   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailySummaryRequest) Reset() {
	*x = GetDailySummaryRequest{}
	mi := &file_diary_diary_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailySummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailySummaryRequest) ProtoMessage() {}

func (x *GetDailySummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailySummaryRequest.ProtoReflect.Descriptor instead.
func (*GetDailySummaryRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{25}
}

func (x *GetDailySummaryRequest) GetDate() *YMD {
	if x != nil {
		return x.Date
	}
	return nil
}

// 日ごとのサマリー取得レスポンス
type GetDailySummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *DailySummary          `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailySummaryResponse) Reset() {
	*x = GetDailySummaryResponse{}
	mi := &file_diary_diary_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailySummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailySummaryResponse) ProtoMessage() {}

func (x *GetDailySummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailySummaryResponse.ProtoReflect.Descriptor instead.
func (*GetDailySummaryResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{26}
}

func (x *GetDailySummaryResponse) GetSummary() *DailySummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

// 直近トレンド分析取得リクエスト
type GetLatestTrendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestTrendRequest) Reset() {
	*x = GetLatestTrendRequest{}
	mi := &file_diary_diary_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestTrendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestTrendRequest) ProtoMessage() {}

func (x *GetLatestTrendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestTrendRequest.ProtoReflect.Descriptor instead.
func (*GetLatestTrendRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{27}
}

// 直近トレンド分析取得レスポンス
type GetLatestTrendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        string                 `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`                                 // 体調: "bad" (悪い), "slight" (やや悪い), "normal" (普通), "good" (良い)
	HealthReason  string                 `protobuf:"bytes,2,opt,name=health_reason,json=healthReason,proto3" json:"health_reason,omitempty"` // 体調の理由（10文字以内）
	Mood          string                 `protobuf:"bytes,3,opt,name=mood,proto3" json:"mood,omitempty"`                                     // 気分: "bad" (悪い), "slight" (やや悪い), "normal" (普通), "good" (良い)
	MoodReason    string                 `protobuf:"bytes,4,opt,name=mood_reason,json=moodReason,proto3" json:"mood_reason,omitempty"`       // 気分の理由（10文字以内）
	Activities    string                 `protobuf:"bytes,5,opt,name=activities,proto3" json:"activities,omitempty"`                         // 活動・行動（箇条書き・階層構造のテキスト）
	PeriodStart   string                 `protobuf:"bytes,6,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`    // 分析期間開始（ISO 8601形式）
	PeriodEnd     string                 `protobuf:"bytes,7,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`          // 分析期間終了（ISO 8601形式）
	GeneratedAt   string                 `protobuf:"bytes,8,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`    // 生成日時（ISO 8601形式）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestTrendResponse) Reset() {
	*x = GetLatestTrendResponse{}
	mi := &file_diary_diary_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestTrendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestTrendResponse) ProtoMessage() {}

func (x *GetLatestTrendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestTrendResponse.ProtoReflect.Descriptor instead.
func (*GetLatestTrendResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{28}
}

func (x *GetLatestTrendResponse) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *GetLatestTrendResponse) GetHealthReason() string {
	if x != nil {
		return x.HealthReason
	}
	return ""
}

func (x *GetLatestTrendResponse) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

func (x *GetLatestTrendResponse) GetMoodReason() string {
	if x != nil {
		return x.MoodReason
	}
	return ""
}

func (x *GetLatestTrendResponse) GetActivities() string {
	if x != nil {
		return x.Activities
	}
	return ""
}

func (x *GetLatestTrendResponse) GetPeriodStart() string {
	if x != nil {
		return x.PeriodStart
	}
	return ""
}

func (x *GetLatestTrendResponse) GetPeriodEnd() string {
	if x != nil {
		return x.PeriodEnd
	}
	return ""
}

func (x *GetLatestTrendResponse) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

// 直近トレンド分析生成トリガーリクエスト（デバッグ用）
type TriggerLatestTrendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerLatestTrendRequest) Reset() {
	*x = TriggerLatestTrendRequest{}
	mi := &file_diary_diary_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerLatestTrendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerLatestTrendRequest) ProtoMessage() {}

func (x *TriggerLatestTrendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerLatestTrendRequest.ProtoReflect.Descriptor instead.
func (*TriggerLatestTrendRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{29}
}

// 直近トレンド分析生成トリガーレスポンス（デバッグ用）
type TriggerLatestTrendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 成功フラグ
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // メッセージ
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerLatestTrendResponse) Reset() {
	*x = TriggerLatestTrendResponse{}
	mi := &file_diary_diary_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerLatestTrendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerLatestTrendResponse) ProtoMessage() {}

func (x *TriggerLatestTrendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerLatestTrendResponse.ProtoReflect.Descriptor instead.
func (*TriggerLatestTrendResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{30}
}

func (x *TriggerLatestTrendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerLatestTrendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 日記ハイライト生成トリガーリクエスト
type TriggerDiaryHighlightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiaryId       string                 `protobuf:"bytes,1,opt,name=diary_id,json=diaryId,proto3" json:"diary_id,omitempty"` // 日記ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerDiaryHighlightRequest) Reset() {
	*x = TriggerDiaryHighlightRequest{}
	mi := &file_diary_diary_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerDiaryHighlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerDiaryHighlightRequest) ProtoMessage() {}

func (x *TriggerDiaryHighlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerDiaryHighlightRequest.ProtoReflect.Descriptor instead.
func (*TriggerDiaryHighlightRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{31}
}

func (x *TriggerDiaryHighlightRequest) GetDiaryId() string {
	if x != nil {
		return x.DiaryId
	}
	return ""
}

// 日記ハイライト生成トリガーレスポンス
type TriggerDiaryHighlightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queued        bool                   `protobuf:"varint,1,opt,name=queued,proto3" json:"queued,omitempty"`  // キューイング成功/失敗
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // メッセージ
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerDiaryHighlightResponse) Reset() {
	*x = TriggerDiaryHighlightResponse{}
	mi := &file_diary_diary_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerDiaryHighlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerDiaryHighlightResponse) ProtoMessage() {}

func (x *TriggerDiaryHighlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerDiaryHighlightResponse.ProtoReflect.Descriptor instead.
func (*TriggerDiaryHighlightResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{32}
}

func (x *TriggerDiaryHighlightResponse) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

func (x *TriggerDiaryHighlightResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 日記ハイライト取得リクエスト
type GetDiaryHighlightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiaryId       string                 `protobuf:"bytes,1,opt,name=diary_id,json=diaryId,proto3" json:"diary_id,omitempty"` // 日記ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiaryHighlightRequest) Reset() {
	*x = GetDiaryHighlightRequest{}
	mi := &file_diary_diary_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiaryHighlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiaryHighlightRequest) ProtoMessage() {}

func (x *GetDiaryHighlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiaryHighlightRequest.ProtoReflect.Descriptor instead.
func (*GetDiaryHighlightRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{33}
}

func (x *GetDiaryHighlightRequest) GetDiaryId() string {
	if x != nil {
		return x.DiaryId
	}
	return ""
}

// ハイライト範囲
type HighlightRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int32                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"` // ハイライト開始位置（文字数）
	End           int32                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`     // ハイライト終了位置（文字数）
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`    // ハイライト対象のテキスト
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HighlightRange) Reset() {
	*x = HighlightRange{}
	mi := &file_diary_diary_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HighlightRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HighlightRange) ProtoMessage() {}

func (x *HighlightRange) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HighlightRange.ProtoReflect.Descriptor instead.
func (*HighlightRange) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{34}
}

func (x *HighlightRange) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *HighlightRange) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *HighlightRange) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// 日記ハイライト取得レスポンス
type GetDiaryHighlightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Highlights    []*HighlightRange      `protobuf:"bytes,1,rep,name=highlights,proto3" json:"highlights,omitempty"`                 // ハイライトリスト
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 作成日時（Unix timestamp）
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 更新日時（Unix timestamp）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiaryHighlightResponse) Reset() {
	*x = GetDiaryHighlightResponse{}
	mi := &file_diary_diary_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiaryHighlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiaryHighlightResponse) ProtoMessage() {}

func (x *GetDiaryHighlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiaryHighlightResponse.ProtoReflect.Descriptor instead.
func (*GetDiaryHighlightResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{35}
}

func (x *GetDiaryHighlightResponse) GetHighlights() []*HighlightRange {
	if x != nil {
		return x.Highlights
	}
	return nil
}

func (x *GetDiaryHighlightResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetDiaryHighlightResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_diary_diary_proto protoreflect.FileDescriptor

const file_diary_diary_proto_rawDesc = "" +
	"\n" +
	"\x11diary/diary.proto\x12\x05diary\"A\n" +
	"\x03YMD\x12\x12\n" +
	"\x04year\x18\x01 \x01(\rR\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\rR\x05month\x12\x10\n" +
	"\x03day\x18\x03 \x01(\rR\x03day\".\n" +
	"\x02YM\x12\x12\n" +
	"\x04year\x18\x01 \x01(\rR\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\rR\x05month\"\x94\x01\n" +
	"\n" +
	"DiaryEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\x04date\x18\x02 \x01(\v2\n" +
	".diary.YMDR\x04date\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"S\n" +
	"\x17CreateDiaryEntryRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1e\n" +
	"\x04date\x18\x02 \x01(\v2\n" +
	".diary.YMDR\x04date\"C\n" +
	"\x18CreateDiaryEntryResponse\x12'\n" +
	"\x05entry\x18\x01 \x01(\v2\x11.diary.DiaryEntryR\x05entry\"6\n" +
	"\x14GetDiaryEntryRequest\x12\x1e\n" +
	"\x04date\x18\x01 \x01(\v2\n" +
	".diary.YMDR\x04date\":\n" +
	"\x16GetDiaryEntriesRequest\x12 \n" +
	"\x05dates\x18\x01 \x03(\v2\n" +
	".diary.YMDR\x05dates\"@\n" +
	"\x1dGetDiaryEntriesByMonthRequest\x12\x1f\n" +
	"\x05month\x18\x01 \x01(\v2\t.diary.YMR\x05month\"5\n" +
	"\x19SearchDiaryEntriesRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\"t\n" +
	"\x1aSearchDiaryEntriesResponse\x12)\n" +
	"\x10searched_keyword\x18\x01 \x01(\tR\x0fsearchedKeyword\x12+\n" +
	"\aentries\x18\x02 \x03(\v2\x11.diary.DiaryEntryR\aentries\"F\n" +
	"\x17GetDiaryEntriesResponse\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.diary.DiaryEntryR\aentries\"M\n" +
	"\x1eGetDiaryEntriesByMonthResponse\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.diary.DiaryEntryR\aentries\"@\n" +
	"\x15GetDiaryEntryResponse\x12'\n" +
	"\x05entry\x18\x01 \x01(\v2\x11.diary.DiaryEntryR\x05entry\"y\n" +
	"\x17UpdateDiaryEntryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1e\n" +
	"\x04date\x18\x04 \x01(\v2\n" +
	".diary.YMDR\x04date\"C\n" +
	"\x18UpdateDiaryEntryResponse\x12'\n" +
	"\x05entry\x18\x01 \x01(\v2\x11.diary.DiaryEntryR\x05entry\")\n" +
	"\x17DeleteDiaryEntryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x18DeleteDiaryEntryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x99\x01\n" +
	"\x0eMonthlySummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\x05month\x18\x02 \x01(\v2\t.diary.YMR\x05month\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"@\n" +
	"\x1dGenerateMonthlySummaryRequest\x12\x1f\n" +
	"\x05month\x18\x01 \x01(\v2\t.diary.YMR\x05month\"Q\n" +
	"\x1eGenerateMonthlySummaryResponse\x12/\n" +
	"\asummary\x18\x01 \x01(\v2\x15.diary.MonthlySummaryR\asummary\";\n" +
	"\x18GetMonthlySummaryRequest\x12\x1f\n" +
	"\x05month\x18\x01 \x01(\v2\t.diary.YMR\x05month\"L\n" +
	"\x19GetMonthlySummaryResponse\x12/\n" +
	"\asummary\x18\x01 \x01(\v2\x15.diary.MonthlySummaryR\asummary\"\xb1\x01\n" +
	"\fDailySummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bdiary_id\x18\x02 \x01(\tR\adiaryId\x12\x1e\n" +
	"\x04date\x18\x03 \x01(\v2\n" +
	".diary.YMDR\x04date\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"8\n" +
	"\x1bGenerateDailySummaryRequest\x12\x19\n" +
	"\bdiary_id\x18\x01 \x01(\tR\adiaryId\"M\n" +
	"\x1cGenerateDailySummaryResponse\x12-\n" +
	"\asummary\x18\x01 \x01(\v2\x13.diary.DailySummaryR\asummary\"8\n" +
	"\x16GetDailySummaryRequest\x12\x1e\n" +
	"\x04date\x18\x01 \x01(\v2\n" +
	".diary.YMDR\x04date\"H\n" +
	"\x17GetDailySummaryResponse\x12-\n" +
	"\asummary\x18\x01 \x01(\v2\x13.diary.DailySummaryR\asummary\"\x17\n" +
	"\x15GetLatestTrendRequest\"\x8f\x02\n" +
	"\x16GetLatestTrendResponse\x12\x16\n" +
	"\x06health\x18\x01 \x01(\tR\x06health\x12#\n" +
	"\rhealth_reason\x18\x02 \x01(\tR\fhealthReason\x12\x12\n" +
	"\x04mood\x18\x03 \x01(\tR\x04mood\x12\x1f\n" +
	"\vmood_reason\x18\x04 \x01(\tR\n" +
	"moodReason\x12\x1e\n" +
	"\n" +
	"activities\x18\x05 \x01(\tR\n" +
	"activities\x12!\n" +
	"\fperiod_start\x18\x06 \x01(\tR\vperiodStart\x12\x1d\n" +
	"\n" +
	"period_end\x18\a \x01(\tR\tperiodEnd\x12!\n" +
	"\fgenerated_at\x18\b \x01(\tR\vgeneratedAt\"\x1b\n" +
	"\x19TriggerLatestTrendRequest\"P\n" +
	"\x1aTriggerLatestTrendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\x1cTriggerDiaryHighlightRequest\x12\x19\n" +
	"\bdiary_id\x18\x01 \x01(\tR\adiaryId\"Q\n" +
	"\x1dTriggerDiaryHighlightResponse\x12\x16\n" +
	"\x06queued\x18\x01 \x01(\bR\x06queued\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\x18GetDiaryHighlightRequest\x12\x19\n" +
	"\bdiary_id\x18\x01 \x01(\tR\adiaryId\"L\n" +
	"\x0eHighlightRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x05R\x03end\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\x90\x01\n" +
	"\x19GetDiaryHighlightResponse\x125\n" +
	"\n" +
	"highlights\x18\x01 \x03(\v2\x15.diary.HighlightRangeR\n" +
	"highlights\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt2\xc5\n" +
	"\n" +
	"\fDiaryService\x12S\n" +
	"\x10CreateDiaryEntry\x12\x1e.diary.CreateDiaryEntryRequest\x1a\x1f.diary.CreateDiaryEntryResponse\x12S\n" +
	"\x10UpdateDiaryEntry\x12\x1e.diary.UpdateDiaryEntryRequest\x1a\x1f.diary.UpdateDiaryEntryResponse\x12S\n" +
	"\x10DeleteDiaryEntry\x12\x1e.diary.DeleteDiaryEntryRequest\x1a\x1f.diary.DeleteDiaryEntryResponse\x12J\n" +
	"\rGetDiaryEntry\x12\x1b.diary.GetDiaryEntryRequest\x1a\x1c.diary.GetDiaryEntryResponse\x12P\n" +
	"\x0fGetDiaryEntries\x12\x1d.diary.GetDiaryEntriesRequest\x1a\x1e.diary.GetDiaryEntriesResponse\x12e\n" +
	"\x16GetDiaryEntriesByMonth\x12$.diary.GetDiaryEntriesByMonthRequest\x1a%.diary.GetDiaryEntriesByMonthResponse\x12Y\n" +
	"\x12SearchDiaryEntries\x12 .diary.SearchDiaryEntriesRequest\x1a!.diary.SearchDiaryEntriesResponse\x12e\n" +
	"\x16GenerateMonthlySummary\x12$.diary.GenerateMonthlySummaryRequest\x1a%.diary.GenerateMonthlySummaryResponse\x12V\n" +
	"\x11GetMonthlySummary\x12\x1f.diary.GetMonthlySummaryRequest\x1a .diary.GetMonthlySummaryResponse\x12_\n" +
	"\x14GenerateDailySummary\x12\".diary.GenerateDailySummaryRequest\x1a#.diary.GenerateDailySummaryResponse\x12P\n" +
	"\x0fGetDailySummary\x12\x1d.diary.GetDailySummaryRequest\x1a\x1e.diary.GetDailySummaryResponse\x12M\n" +
	"\x0eGetLatestTrend\x12\x1c.diary.GetLatestTrendRequest\x1a\x1d.diary.GetLatestTrendResponse\x12Y\n" +
	"\x12TriggerLatestTrend\x12 .diary.TriggerLatestTrendRequest\x1a!.diary.TriggerLatestTrendResponse\x12b\n" +
	"\x15TriggerDiaryHighlight\x12#.diary.TriggerDiaryHighlightRequest\x1a$.diary.TriggerDiaryHighlightResponse\x12V\n" +
	"\x11GetDiaryHighlight\x12\x1f.diary.GetDiaryHighlightRequest\x1a .diary.GetDiaryHighlightResponseB@Z>github.com/project-mikan/umi.mikan/backend/infrastructure/grpcb\x06proto3"

var (
	file_diary_diary_proto_rawDescOnce sync.Once
	file_diary_diary_proto_rawDescData []byte
)

func file_diary_diary_proto_rawDescGZIP() []byte {
	file_diary_diary_proto_rawDescOnce.Do(func() {
		file_diary_diary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_diary_diary_proto_rawDesc), len(file_diary_diary_proto_rawDesc)))
	})
	return file_diary_diary_proto_rawDescData
}

var file_diary_diary_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_diary_diary_proto_goTypes = []any{
	(*YMD)(nil),                            // 0: diary.YMD
	(*YM)(nil),                             // 1: diary.YM
	(*DiaryEntry)(nil),                     // 2: diary.DiaryEntry
	(*CreateDiaryEntryRequest)(nil),        // 3: diary.CreateDiaryEntryRequest
	(*CreateDiaryEntryResponse)(nil),       // 4: diary.CreateDiaryEntryResponse
	(*GetDiaryEntryRequest)(nil),           // 5: diary.GetDiaryEntryRequest
	(*GetDiaryEntriesRequest)(nil),         // 6: diary.GetDiaryEntriesRequest
	(*GetDiaryEntriesByMonthRequest)(nil),  // 7: diary.GetDiaryEntriesByMonthRequest
	(*SearchDiaryEntriesRequest)(nil),      // 8: diary.SearchDiaryEntriesRequest
	(*SearchDiaryEntriesResponse)(nil),     // 9: diary.SearchDiaryEntriesResponse
	(*GetDiaryEntriesResponse)(nil),        // 10: diary.GetDiaryEntriesResponse
	(*GetDiaryEntriesByMonthResponse)(nil), // 11: diary.GetDiaryEntriesByMonthResponse
	(*GetDiaryEntryResponse)(nil),          // 12: diary.GetDiaryEntryResponse
	(*UpdateDiaryEntryRequest)(nil),        // 13: diary.UpdateDiaryEntryRequest
	(*UpdateDiaryEntryResponse)(nil),       // 14: diary.UpdateDiaryEntryResponse
	(*DeleteDiaryEntryRequest)(nil),        // 15: diary.DeleteDiaryEntryRequest
	(*DeleteDiaryEntryResponse)(nil),       // 16: diary.DeleteDiaryEntryResponse
	(*MonthlySummary)(nil),                 // 17: diary.MonthlySummary
	(*GenerateMonthlySummaryRequest)(nil),  // 18: diary.GenerateMonthlySummaryRequest
	(*GenerateMonthlySummaryResponse)(nil), // 19: diary.GenerateMonthlySummaryResponse
	(*GetMonthlySummaryRequest)(nil),       // 20: diary.GetMonthlySummaryRequest
	(*GetMonthlySummaryResponse)(nil),      // 21: diary.GetMonthlySummaryResponse
	(*DailySummary)(nil),                   // 22: diary.DailySummary
	(*GenerateDailySummaryRequest)(nil),    // 23: diary.GenerateDailySummaryRequest
	(*GenerateDailySummaryResponse)(nil),   // 24: diary.GenerateDailySummaryResponse
	(*GetDailySummaryRequest)(nil),         // 25: diary.GetDailySummaryRequest
	(*GetDailySummaryResponse)(nil),        // 26: diary.GetDailySummaryResponse
	(*GetLatestTrendRequest)(nil),          // 27: diary.GetLatestTrendRequest
	(*GetLatestTrendResponse)(nil),         // 28: diary.GetLatestTrendResponse
	(*TriggerLatestTrendRequest)(nil),      // 29: diary.TriggerLatestTrendRequest
	(*TriggerLatestTrendResponse)(nil),     // 30: diary.TriggerLatestTrendResponse
	(*TriggerDiaryHighlightRequest)(nil),   // 31: diary.TriggerDiaryHighlightRequest
	(*TriggerDiaryHighlightResponse)(nil),  // 32: diary.TriggerDiaryHighlightResponse
	(*GetDiaryHighlightRequest)(nil),       // 33: diary.GetDiaryHighlightRequest
	(*HighlightRange)(nil),                 // 34: diary.HighlightRange
	(*GetDiaryHighlightResponse)(nil),      // 35: diary.GetDiaryHighlightResponse
}
var file_diary_diary_proto_depIdxs = []int32{
	0,  // 0: diary.DiaryEntry.date:type_name -> diary.YMD
	0,  // 1: diary.CreateDiaryEntryRequest.date:type_name -> diary.YMD
	2,  // 2: diary.CreateDiaryEntryResponse.entry:type_name -> diary.DiaryEntry
	0,  // 3: diary.GetDiaryEntryRequest.date:type_name -> diary.YMD
	0,  // 4: diary.GetDiaryEntriesRequest.dates:type_name -> diary.YMD
	1,  // 5: diary.GetDiaryEntriesByMonthRequest.month:type_name -> diary.YM
	2,  // 6: diary.SearchDiaryEntriesResponse.entries:type_name -> diary.DiaryEntry
	2,  // 7: diary.GetDiaryEntriesResponse.entries:type_name -> diary.DiaryEntry
	2,  // 8: diary.GetDiaryEntriesByMonthResponse.entries:type_name -> diary.DiaryEntry
	2,  // 9: diary.GetDiaryEntryResponse.entry:type_name -> diary.DiaryEntry
	0,  // 10: diary.UpdateDiaryEntryRequest.date:type_name -> diary.YMD
	2,  // 11: diary.UpdateDiaryEntryResponse.entry:type_name -> diary.DiaryEntry
	1,  // 12: diary.MonthlySummary.month:type_name -> diary.YM
	1,  // 13: diary.GenerateMonthlySummaryRequest.month:type_name -> diary.YM
	17, // 14: diary.GenerateMonthlySummaryResponse.summary:type_name -> diary.MonthlySummary
	1,  // 15: diary.GetMonthlySummaryRequest.month:type_name -> diary.YM
	17, // 16: diary.GetMonthlySummaryResponse.summary:type_name -> diary.MonthlySummary
	0,  // 17: diary.DailySummary.date:type_name -> diary.YMD
	22, // 18: diary.GenerateDailySummaryResponse.summary:type_name -> diary.DailySummary
	0,  // 19: diary.GetDailySummaryRequest.date:type_name -> diary.YMD
	22, // 20: diary.GetDailySummaryResponse.summary:type_name -> diary.DailySummary
	34, // 21: diary.GetDiaryHighlightResponse.highlights:type_name -> diary.HighlightRange
	3,  // 22: diary.DiaryService.CreateDiaryEntry:input_type -> diary.CreateDiaryEntryRequest
	13, // 23: diary.DiaryService.UpdateDiaryEntry:input_type -> diary.UpdateDiaryEntryRequest
	15, // 24: diary.DiaryService.DeleteDiaryEntry:input_type -> diary.DeleteDiaryEntryRequest
	5,  // 25: diary.DiaryService.GetDiaryEntry:input_type -> diary.GetDiaryEntryRequest
	6,  // 26: diary.DiaryService.GetDiaryEntries:input_type -> diary.GetDiaryEntriesRequest
	7,  // 27: diary.DiaryService.GetDiaryEntriesByMonth:input_type -> diary.GetDiaryEntriesByMonthRequest
	8,  // 28: diary.DiaryService.SearchDiaryEntries:input_type -> diary.SearchDiaryEntriesRequest
	18, // 29: diary.DiaryService.GenerateMonthlySummary:input_type -> diary.GenerateMonthlySummaryRequest
	20, // 30: diary.DiaryService.GetMonthlySummary:input_type -> diary.GetMonthlySummaryRequest
	23, // 31: diary.DiaryService.GenerateDailySummary:input_type -> diary.GenerateDailySummaryRequest
	25, // 32: diary.DiaryService.GetDailySummary:input_type -> diary.GetDailySummaryRequest
	27, // 33: diary.DiaryService.GetLatestTrend:input_type -> diary.GetLatestTrendRequest
	29, // 34: diary.DiaryService.TriggerLatestTrend:input_type -> diary.TriggerLatestTrendRequest
	31, // 35: diary.DiaryService.TriggerDiaryHighlight:input_type -> diary.TriggerDiaryHighlightRequest
	33, // 36: diary.DiaryService.GetDiaryHighlight:input_type -> diary.GetDiaryHighlightRequest
	4,  // 37: diary.DiaryService.CreateDiaryEntry:output_type -> diary.CreateDiaryEntryResponse
	14, // 38: diary.DiaryService.UpdateDiaryEntry:output_type -> diary.UpdateDiaryEntryResponse
	16, // 39: diary.DiaryService.DeleteDiaryEntry:output_type -> diary.DeleteDiaryEntryResponse
	12, // 40: diary.DiaryService.GetDiaryEntry:output_type -> diary.GetDiaryEntryResponse
	10, // 41: diary.DiaryService.GetDiaryEntries:output_type -> diary.GetDiaryEntriesResponse
	11, // 42: diary.DiaryService.GetDiaryEntriesByMonth:output_type -> diary.GetDiaryEntriesByMonthResponse
	9,  // 43: diary.DiaryService.SearchDiaryEntries:output_type -> diary.SearchDiaryEntriesResponse
	19, // 44: diary.DiaryService.GenerateMonthlySummary:output_type -> diary.GenerateMonthlySummaryResponse
	21, // 45: diary.DiaryService.GetMonthlySummary:output_type -> diary.GetMonthlySummaryResponse
	24, // 46: diary.DiaryService.GenerateDailySummary:output_type -> diary.GenerateDailySummaryResponse
	26, // 47: diary.DiaryService.GetDailySummary:output_type -> diary.GetDailySummaryResponse
	28, // 48: diary.DiaryService.GetLatestTrend:output_type -> diary.GetLatestTrendResponse
	30, // 49: diary.DiaryService.TriggerLatestTrend:output_type -> diary.TriggerLatestTrendResponse
	32, // 50: diary.DiaryService.TriggerDiaryHighlight:output_type -> diary.TriggerDiaryHighlightResponse
	35, // 51: diary.DiaryService.GetDiaryHighlight:output_type -> diary.GetDiaryHighlightResponse
	37, // [37:52] is the sub-list for method output_type
	22, // [22:37] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_diary_diary_proto_init() }
func file_diary_diary_proto_init() {
	if File_diary_diary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_diary_diary_proto_rawDesc), len(file_diary_diary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_diary_diary_proto_goTypes,
		DependencyIndexes: file_diary_diary_proto_depIdxs,
		MessageInfos:      file_diary_diary_proto_msgTypes,
	}.Build()
	File_diary_diary_proto = out.File
	file_diary_diary_proto_goTypes = nil
	file_diary_diary_proto_depIdxs = nil
}
