// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: entity/entity.proto
//

import Connect
import Foundation
import SwiftProtobuf

/// EntityService は固有名詞（人物、場所など）を管理するサービスです。
/// エンティティは日記本文中で使用され、ハイライト表示や検索に利用されます。
internal protocol Entity_EntityServiceClientInterface: Sendable {

    /// CreateEntity は新しいエンティティを作成します。
    ///
    /// 例:
    ///   request: { name: "山田太郎", category: PEOPLE, memo: "友人" }
    ///   response: { entity: { id: "uuid", name: "山田太郎", ... } }
    ///
    /// エラー:
    ///   - AlreadyExists: 同じ名前のエンティティまたはエイリアスが既に存在する
    @available(iOS 13, *)
    func `createEntity`(request: Entity_CreateEntityRequest, headers: Connect.Headers) async -> ResponseMessage<Entity_CreateEntityResponse>

    /// UpdateEntity は既存のエンティティを更新します。
    ///
    /// 例:
    ///   request: { id: "uuid", name: "山田花子", category: PEOPLE, memo: "同僚" }
    ///
    /// エラー:
    ///   - NotFound: エンティティが見つからない
    ///   - PermissionDenied: 他のユーザーのエンティティにアクセスしようとした
    @available(iOS 13, *)
    func `updateEntity`(request: Entity_UpdateEntityRequest, headers: Connect.Headers) async -> ResponseMessage<Entity_UpdateEntityResponse>

    /// DeleteEntity はエンティティとそれに紐づくエイリアスを削除します。
    ///
    /// エラー:
    ///   - NotFound: エンティティが見つからない
    ///   - PermissionDenied: 他のユーザーのエンティティにアクセスしようとした
    @available(iOS 13, *)
    func `deleteEntity`(request: Entity_DeleteEntityRequest, headers: Connect.Headers) async -> ResponseMessage<Entity_DeleteEntityResponse>

    /// GetEntity は指定されたIDのエンティティを取得します。
    /// エイリアスも含めて返されます。
    ///
    /// エラー:
    ///   - NotFound: エンティティが見つからない
    ///   - PermissionDenied: 他のユーザーのエンティティにアクセスしようとした
    @available(iOS 13, *)
    func `getEntity`(request: Entity_GetEntityRequest, headers: Connect.Headers) async -> ResponseMessage<Entity_GetEntityResponse>

    /// ListEntities はユーザーのエンティティ一覧を取得します。
    /// カテゴリでフィルタリングも可能です。
    ///
    /// 例（全件取得）:
    ///   request: { all_categories: true }
    ///
    /// 例（カテゴリフィルタ）:
    ///   request: { category: PEOPLE, all_categories: false }
    @available(iOS 13, *)
    func `listEntities`(request: Entity_ListEntitiesRequest, headers: Connect.Headers) async -> ResponseMessage<Entity_ListEntitiesResponse>

    /// CreateEntityAlias はエンティティにエイリアス（別名）を追加します。
    ///
    /// 例:
    ///   request: { entity_id: "uuid", alias: "太郎" }
    ///
    /// エラー:
    ///   - AlreadyExists: 同じエイリアスまたはエンティティ名が既に存在する
    ///   - PermissionDenied: 他のユーザーのエンティティにアクセスしようとした
    @available(iOS 13, *)
    func `createEntityAlias`(request: Entity_CreateEntityAliasRequest, headers: Connect.Headers) async -> ResponseMessage<Entity_CreateEntityAliasResponse>

    /// UpdateEntityAlias はエイリアスを更新します。
    ///
    /// 例:
    ///   request: { id: "uuid", alias: "太郎くん" }
    ///
    /// エラー:
    ///   - NotFound: エイリアスが見つからない
    ///   - AlreadyExists: 同じエイリアスまたはエンティティ名が既に存在する
    ///   - PermissionDenied: 他のユーザーのエンティティのエイリアスにアクセスしようとした
    @available(iOS 13, *)
    func `updateEntityAlias`(request: Entity_UpdateEntityAliasRequest, headers: Connect.Headers) async -> ResponseMessage<Entity_UpdateEntityAliasResponse>

    /// DeleteEntityAlias はエイリアスを削除します。
    ///
    /// エラー:
    ///   - NotFound: エイリアスが見つからない
    ///   - PermissionDenied: 他のユーザーのエンティティのエイリアスにアクセスしようとした
    @available(iOS 13, *)
    func `deleteEntityAlias`(request: Entity_DeleteEntityAliasRequest, headers: Connect.Headers) async -> ResponseMessage<Entity_DeleteEntityAliasResponse>

    /// SearchEntities はエンティティ名またはエイリアスで部分一致検索を行います。
    /// 主に日記入力時の補完候補として使用されます。
    ///
    /// 例:
    ///   request: { query: "山田" }
    ///   response: { entities: [{ name: "山田太郎", ... }, { name: "山田花子", ... }] }
    ///
    /// 空文字列を指定すると全件取得されます。
    @available(iOS 13, *)
    func `searchEntities`(request: Entity_SearchEntitiesRequest, headers: Connect.Headers) async -> ResponseMessage<Entity_SearchEntitiesResponse>
}

/// Concrete implementation of `Entity_EntityServiceClientInterface`.
internal final class Entity_EntityServiceClient: Entity_EntityServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    internal init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    internal func `createEntity`(request: Entity_CreateEntityRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Entity_CreateEntityResponse> {
        return await self.client.unary(path: "/entity.EntityService/CreateEntity", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `updateEntity`(request: Entity_UpdateEntityRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Entity_UpdateEntityResponse> {
        return await self.client.unary(path: "/entity.EntityService/UpdateEntity", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `deleteEntity`(request: Entity_DeleteEntityRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Entity_DeleteEntityResponse> {
        return await self.client.unary(path: "/entity.EntityService/DeleteEntity", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `getEntity`(request: Entity_GetEntityRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Entity_GetEntityResponse> {
        return await self.client.unary(path: "/entity.EntityService/GetEntity", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `listEntities`(request: Entity_ListEntitiesRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Entity_ListEntitiesResponse> {
        return await self.client.unary(path: "/entity.EntityService/ListEntities", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `createEntityAlias`(request: Entity_CreateEntityAliasRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Entity_CreateEntityAliasResponse> {
        return await self.client.unary(path: "/entity.EntityService/CreateEntityAlias", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `updateEntityAlias`(request: Entity_UpdateEntityAliasRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Entity_UpdateEntityAliasResponse> {
        return await self.client.unary(path: "/entity.EntityService/UpdateEntityAlias", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `deleteEntityAlias`(request: Entity_DeleteEntityAliasRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Entity_DeleteEntityAliasResponse> {
        return await self.client.unary(path: "/entity.EntityService/DeleteEntityAlias", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    internal func `searchEntities`(request: Entity_SearchEntitiesRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Entity_SearchEntitiesResponse> {
        return await self.client.unary(path: "/entity.EntityService/SearchEntities", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    internal enum Metadata {
        internal enum Methods {
            internal static let createEntity = Connect.MethodSpec(name: "CreateEntity", service: "entity.EntityService", type: .unary)
            internal static let updateEntity = Connect.MethodSpec(name: "UpdateEntity", service: "entity.EntityService", type: .unary)
            internal static let deleteEntity = Connect.MethodSpec(name: "DeleteEntity", service: "entity.EntityService", type: .unary)
            internal static let getEntity = Connect.MethodSpec(name: "GetEntity", service: "entity.EntityService", type: .unary)
            internal static let listEntities = Connect.MethodSpec(name: "ListEntities", service: "entity.EntityService", type: .unary)
            internal static let createEntityAlias = Connect.MethodSpec(name: "CreateEntityAlias", service: "entity.EntityService", type: .unary)
            internal static let updateEntityAlias = Connect.MethodSpec(name: "UpdateEntityAlias", service: "entity.EntityService", type: .unary)
            internal static let deleteEntityAlias = Connect.MethodSpec(name: "DeleteEntityAlias", service: "entity.EntityService", type: .unary)
            internal static let searchEntities = Connect.MethodSpec(name: "SearchEntities", service: "entity.EntityService", type: .unary)
        }
    }
}
