name: 【infra】PR自動ラベル付与
on:
  - pull_request

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/labeler@v5
