name: 【frontend】Biome Lint & Format

on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/**"

jobs:
  biome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "frontend/package.json"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: frontend/package.json

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm install

      - name: Run Biome check
        working-directory: ./frontend
        run: pnpm run lint
