name: Build Docker Image (Reusable)

on:
  workflow_call:
    inputs:
      service_name:
        description: 'Service name (e.g., backend, frontend, scheduler, subscriber)'
        required: true
        type: string
      dockerfile_path:
        description: 'Path to Dockerfile relative to repository root'
        required: true
        type: string
      context_path:
        description: 'Build context path (default: .)'
        required: false
        type: string
        default: '.'
      image_name:
        description: 'Docker image name (default: umi-mikan-{service_name})'
        required: false
        type: string
        default: ''

jobs:
  push_to_registry:
    name: Push ${{ inputs.service_name }} Docker image to GitHub Container Registry
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-${{ inputs.service_name }}
          key: ${{ runner.os }}-buildx-${{ inputs.service_name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ inputs.service_name }}-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # arm64とamd64両対応のため
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set image name
        id: image_name
        run: |
          if [ -n "${{ inputs.image_name }}" ]; then
            echo "name=${{ inputs.image_name }}" >> $GITHUB_OUTPUT
          else
            echo "name=umi-mikan-${{ inputs.service_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push ${{ inputs.service_name }} to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context_path }}
          file: ${{ inputs.dockerfile_path }}
          push: true
          platforms: linux/arm64,linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ steps.image_name.outputs.name }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ steps.image_name.outputs.name }}:latest
          labels: latest
          cache-from: type=local,src=/tmp/.buildx-cache-${{ inputs.service_name }}
          cache-to: type=local,dest=/tmp/.buildx-cache-${{ inputs.service_name }}-new,mode=max

        # 現状まだキャッシュ自動削除の仕組みができていないらしい→https://docs.docker.com/build/ci/github-actions/cache/
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-${{ inputs.service_name }}
          mv /tmp/.buildx-cache-${{ inputs.service_name }}-new /tmp/.buildx-cache-${{ inputs.service_name }}